project_name        = "java-app"
project_environment = "production"
domain_name         = "chottu.shop"
hostname            = "jav-app"
instance_type       = "t2.micro"
ami_id              = "ami-0a1235697f4afa8a4"
